require conf/machine/include/rv1106.inc

UBOOT_MACHINE = "rv1106_defconfig"

KERNEL_DEVICETREE ?= "rv1106g-luckfox-pico-max.dtb"

RK_ENV_PART ?= "32K(env),512K@32K(idblock),256K(uboot),32M(boot),1G(rootfs)"
RK_BOOTARGS_CMA_SIZE ?= "66M"
