require conf/machine/include/rv1106.inc

UBOOT_MACHINE = "rv1106_defconfig"

KERNEL_DEVICETREE ?= "rv1103g-luckfox-pico-mini.dtb"
SDCARD_ROOTFS ?= "${DEPLOY_DIR_IMAGE}/${IMAGE_NAME}.rootfs.ext4"

RK_ENV_PART ?= "32K(env),512K@32K(idblock),256K(uboot),32M(boot),1G(rootfs)"
RK_BOOTMEDIA ?= "emmc"