# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-luckfox-pico"
BBFILE_PATTERN_meta-luckfox-pico = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-luckfox-pico = "6"

LAYERDEPENDS_meta-luckfox-pico = "core"
LAYERSERIES_COMPAT_meta-luckfox-pico = "scarthgap"

addpylib ${LAYERDIR}/lib envimage
